# Generated by Django 2.2.7 on 2021-07-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAP_Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.PositiveIntegerField(null=True)),
                ('Year', models.PositiveIntegerField(default=2021, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('SAP_Filter', models.FileField(upload_to='SAP_Filter1')),
                ('Year_Week', models.CharField(blank=True, max_length=7, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary_All_Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.PositiveIntegerField(null=True)),
                ('Year', models.PositiveIntegerField(default=2021, null=True)),
                ('summary_all_program', models.FileField(upload_to='Summary_All_Program')),
                ('sheetname', models.CharField(blank=True, default='LIST', max_length=254, null=True)),
                ('Year_Week', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary_All_Program_Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.PositiveIntegerField(null=True)),
                ('Year', models.PositiveIntegerField(default=2021, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Year_Week', models.CharField(blank=True, max_length=7, null=True)),
                ('SAP_Filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SAP_Filter1', to='Summary_All_Program.SAP_Filter')),
                ('summary_all_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Summary_All_Program1', to='Summary_All_Program.Summary_All_Program')),
            ],
        ),
    ]
