# Generated by Django 2.2.7 on 2021-07-09 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nodin', '0004_auto_20210709_0819'),
        ('RNC', '0002_auto_20210709_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodin_To_Tpass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('tpass_fields', models.FileField(upload_to='Tpass')),
                ('date', models.DateTimeField(auto_now=True)),
                ('Week', models.PositiveIntegerField(null=True)),
                ('Year', models.PositiveIntegerField(default=2021, null=True)),
                ('Nodin_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nodin1', to='Nodin.Nodin')),
                ('RNC_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RNC1', to='RNC.RNC')),
            ],
        ),
    ]
