# Generated by Django 2.2.7 on 2021-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meas',
            name='Year_Week',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
