# Generated by Django 2.2.7 on 2021-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Nodin', models.FileField(upload_to='Nodin')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
