# Generated by Django 2.2.7 on 2021-07-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nodin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodin',
            name='Year',
            field=models.PositiveIntegerField(default=2021, null=True),
        ),
    ]
