# Generated by Django 2.2.7 on 2021-07-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nodin', '0002_nodin_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodin',
            old_name='date',
            new_name='date_field',
        ),
    ]
