# Generated by Django 2.2.7 on 2021-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week', models.PositiveIntegerField(null=True)),
                ('Year', models.PositiveIntegerField(default=2021, null=True)),
                ('site_id_profile', models.FileField(upload_to='Site_ID_Profile')),
                ('Year_Week', models.CharField(blank=True, max_length=7, null=True, unique=True)),
            ],
        ),
    ]
