# Generated by Django 2.2.7 on 2021-07-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Site_Profile', '0001_initial'),
        ('Meas', '0002_auto_20210712_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOC_Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year_Week', models.CharField(blank=True, max_length=500, null=True)),
                ('NOC_fields', models.FileField(blank=True, upload_to='NOC')),
                ('date', models.DateTimeField(auto_now=True)),
                ('Week', models.PositiveIntegerField(null=True)),
                ('Year', models.PositiveIntegerField(default=2021, null=True)),
                ('cw_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meas2', to='Meas.Meas')),
                ('lw_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meas1', to='Meas.Meas')),
                ('site_profile_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meas2', to='Site_Profile.Site_Profile')),
            ],
        ),
    ]
