# Generated by Django 2.2.7 on 2021-07-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nodin_to_Tpass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodin_to_tpass',
            name='tpass_fields',
            field=models.FileField(blank=True, upload_to='Tpass'),
        ),
    ]
