# Generated by Django 2.2.7 on 2021-07-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_Overview_Current', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noc_processing',
            name='Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noc_processing',
            name='Year_Week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
