# Generated by Django 2.2.7 on 2021-07-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Network_Overview_Current', '0002_auto_20210713_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noc_processing',
            old_name='date',
            new_name='date_field',
        ),
    ]
