# Generated by Django 2.2.7 on 2021-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meas2G', models.FileField(upload_to='Meas2G')),
                ('Meas3G', models.FileField(upload_to='Meas3G')),
                ('Meas4G', models.FileField(upload_to='Meas4G')),
                ('Week', models.PositiveIntegerField(null=True)),
                ('Year', models.PositiveIntegerField(default=2021, null=True)),
                ('Year_Week', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('date_field', models.DateField(auto_now=True)),
            ],
        ),
    ]
